In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('E:\machine\MachineLearning\DataSets\Social_Network_Ads.csv')

In [3]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB


In [5]:
X = data.iloc[:,2:4].values

In [6]:
y = data.iloc[:,4].values

In [7]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [9]:
X_train

array([[    36, 118000],
       [    58, 101000],
       [    19,  25000],
       [    24,  19000],
       [    42,  70000],
       [    36,  99000],
       [    34,  43000],
       [    38,  80000],
       [    26,  30000],
       [    26,  80000],
       [    55,  39000],
       [    41,  72000],
       [    40,  57000],
       [    48, 141000],
       [    49,  74000],
       [    39,  71000],
       [    26,  80000],
       [    25,  22000],
       [    51, 146000],
       [    18,  86000],
       [    35,  75000],
       [    48,  90000],
       [    50,  88000],
       [    60,  42000],
       [    32, 150000],
       [    23,  20000],
       [    60,  46000],
       [    20,  36000],
       [    58, 144000],
       [    37, 144000],
       [    36,  63000],
       [    37,  79000],
       [    41,  71000],
       [    43, 129000],
       [    47,  49000],
       [    23,  66000],
       [    30,  17000],
       [    26,  35000],
       [    34, 112000],
       [    47,  43000],


In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc = StandardScaler()

In [12]:
X_train = sc.fit_transform(X_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [13]:
X_test = sc.transform(X_test)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [14]:
X_train

array([[-0.16911522,  1.40272371],
       [ 1.92696076,  0.89973663],
       [-1.7888103 , -1.34891149],
       [-1.31242939, -1.52643634],
       [ 0.40254186, -0.0174751 ],
       [-0.16911522,  0.84056168],
       [-0.35966758, -0.81633694],
       [ 0.02143714,  0.27839965],
       [-1.12187703, -1.20097412],
       [-1.12187703,  0.27839965],
       [ 1.64113222, -0.93468684],
       [ 0.30726568,  0.04169985],
       [ 0.2119895 , -0.40211228],
       [ 0.97419895,  2.08323564],
       [ 1.06947513,  0.1008748 ],
       [ 0.11671332,  0.01211237],
       [-1.12187703,  0.27839965],
       [-1.21715321, -1.43767392],
       [ 1.26002749,  2.23117302],
       [-1.88408648,  0.4559245 ],
       [-0.2643914 ,  0.13046227],
       [ 0.97419895,  0.5742744 ],
       [ 1.16475131,  0.51509945],
       [ 2.11751312, -0.84592441],
       [-0.55021994,  2.34952292],
       [-1.40770557, -1.49684887],
       [ 2.11751312, -0.72757451],
       [-1.69353412, -1.02344926],
       [ 1.92696076,

In [15]:
X_test

array([[ 0.02143714, -0.60922461],
       [ 0.40254186,  1.10684896],
       [-0.83604849,  0.36716208],
       [-0.35966758,  1.31396129],
       [ 0.97419895, -1.23056159],
       [-0.16911522, -0.31334986],
       [-0.55021994,  1.37313624],
       [-1.88408648, -0.55004966],
       [-0.74077231, -1.64478624],
       [ 1.16475131, -1.49684887],
       [-0.16911522, -0.60922461],
       [-0.74077231,  0.54468693],
       [-0.2643914 ,  0.07128732],
       [ 0.11671332,  0.01211237],
       [ 0.30726568, -0.55004966],
       [ 0.02143714, -0.46128723],
       [ 0.2119895 ,  0.01211237],
       [-0.45494376, -1.26014907],
       [-0.2643914 , -0.60922461],
       [ 1.45057985,  0.3375746 ],
       [-0.07383904,  0.1008748 ],
       [ 2.11751312, -1.08262421],
       [ 1.64113222,  1.60983604],
       [-1.02660085,  0.5742744 ],
       [ 2.11751312,  1.10684896],
       [-1.69353412,  0.3375746 ],
       [-1.12187703, -1.61519877],
       [-1.02660085, -0.40211228],
       [-0.2643914 ,

In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
gnb = GaussianNB()

In [18]:
gnb.fit(X_train,y_train)

GaussianNB(priors=None)

In [19]:
y_predictor = gnb.predict(X_test)

In [20]:
y_predictor

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
cm = confusion_matrix(y_test,y_predictor)

In [23]:
cm

array([[51,  3],
       [ 4, 22]], dtype=int64)